// Generated by CoffeeScript 1.10.0
var aws, s3, settings;

aws = require('aws-sdk');

s3 = new aws.S3();

settings = {
  bucketName: 'test-lambda-backet',
  postsDir: 'posts/'
};

exports.handler = function(event, context) {
  return s3.getObject({
    Bucket: settings.bucketName,
    Key: 'config.json'
  }, function(err, data) {
    var config;
    if (err) {
      config = {
        posts: {}
      };
    } else {
      config = JSON.parse(data.Body.toString('UTF-8'));
    }
    return s3.putObject({
      Bucket: settings.bucketName,
      Key: "" + settings.postsDir + event.postName,
      Body: event.body
    }, function(err, data) {
      var post;
      if (err) {
        return context.done(err);
      }
      post = {
        title: event.title,
        publishDate: new Date(event.publishDate),
        category: event.category
      };
      config.posts[event.postName] = post;
      return s3.putObject({
        Bucket: settings.bucketName,
        Key: 'config.json',
        Body: JSON.stringify(config)
      }, function(err, data) {
        if (err) {
          return context.done(err);
        } else {
          return context.succeed(event.body);
        }
      });
    });
  });
};
